build-container-x86-64:
  image: docker:19.03.12
  stage: container-x86-64
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/x86-64:main
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f ci/x86-64.dockerfile .
    - docker push $IMAGE_TAG
  timeout: 3 hours
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_TITLE =~ /chore\(version\)\:.*/'
      when: never
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - ci/x86-64.dockerfile
        - ci/.gitlab-ci-containers.yml
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - ci/x86-64.dockerfile
        - ci/.gitlab-ci-containers.yml
